### ISSUE TITLE
Just A Question

### ISSUE THREAD

**Issue by UnstableWifi** [Expugn/S-argo#10]
Does the More Deban Mod still active. If so, how do I do it as of now.

**Comment by Expugn** [comment]
nah. it's outdated since I updated the whole `ScoutMaster` system. guess you could update it yourself (paste the links over the template) if you want to use it.

**Comment by UnstableWifi** [comment]
I guess its fine. It seemed like something cool to add. What did it do?

**Comment by Expugn** [comment]
it was just the More Deban Liz/Silica overlayed over the Argo you see when you perform scouts, similar to what the game did on April Fools.
