### ISSUE TITLE
Problem with download file

### ISSUE THREAD

**Issue by SicuramenteDave** [Expugn/S-argo#11]
When i launch the .jar file, after the reading token and access, when download the file, it found 0 file.
This is the error log:

12:46:34.765 DEBUG i.g.spugn.Sargo.Functions.Update - Downloading System Images...
12:46:34.774 DEBUG i.g.spugn.Sargo.Functions.Update - 0 files downloaded.
12:46:34.775 DEBUG i.g.spugn.Sargo.Functions.Update - Downloading Item Images...
12:46:34.778 DEBUG i.g.spugn.Sargo.Functions.Update - 0 files downloaded.
12:46:34.783 DEBUG i.g.spugn.Sargo.Functions.Reload - Reloading Banners.xml...
FAILED TO READ BANNER FILE - An error has occurred when trying to read the Banner file.
Try restarting the bot or correct the issue manually.
Error Code: 101
12:46:34.794 DEBUG i.g.spugn.Sargo.Functions.Reload - 0 banners loaded.

**Comment by Expugn** [comment]
From the Startup Guide:

```
Wait! The setup process isn't done yet! Run the command update r to grab the latest Banners.xml file and all the new images automatically.
[⚠️] To run a command, you can either mention your bot or use the default command prefix ($).
So, you can either use @YourBotName update r OR $update r.
```

make sure you have run `$update r` (by default)
