### ISSUE TITLE
Problems Running .jar File

### ISSUE THREAD

**Issue by isaaclim98** [Expugn/S-argo#6]
### Bot Version
v2.1
### Type of Issue
Nothing happens after running the .jar file.
### Bug Summary
I have followed all the steps in the guide to setup the bot from scratch, however, when I right click the .jar file and "Open With..." -> "Java(TM) Platform SE Binary", nothing happens at all, the bot does not go online in the Discord server either.

### How to Reproduce the Issue
It happens at Step 5 of the guide you've graciously provided, when I run the .jar file. I'm unsure if having WinRAR installed interferes in any way.

**Comment by Expugn** [comment]
Assuming you obtained the latest `Settings.xml` file, can you tell me what settings you modified?

One reason why the bot may shut down for no reason at startup is if a system file does not exist in the Data Repository. If you are using a custom Data Repository, you may be missing 2 files that were added since the `v2.1` update which is `Rarity_Star.png` and `Empty_Rarity_Star.png`.

**Comment by isaaclim98** [comment]
So far I've only modified and replaced YOUR_BOT_TOKEN_HERE and BOT_OWNER_DISCORD_ID_HERE with the respective items. And thank you for such a quick reply! :)

**Comment by Expugn** [comment]
Are you inserting the correct bot token? 

The bot token can be found here: https://i.imgur.com/4n0XR6z.png

**Comment by isaaclim98** [comment]
Yup, I've inserted that token from there, even going as far to generate new tokens and changing the token in the Settings.xml file every time I've done so.

**Comment by Expugn** [comment]
Alright, if you can, do these two things for me:

1) (assuming you're on a Windows OS) open up Notepad  
2) type `java -jar Sargo.jar`  
3) File -> Save As  
4) Change `Save as type:` to `All Files`  
5) Save the file as `run.bat` and put it in the same folder as where your .jar is.

You can now see the console output if you double click `run.bat`. If you can, copy-paste the part where it stops here.

for the second thing:

paste the full settings.xml file here (you'll have to change your bot token afterwards though)

meanwhile, i'll try setting up a fresh copy myself to see how that goes

**Comment by isaaclim98** [comment]
Here's the first thing:
https://imgur.com/a/bKktO

And for the second:
[Settings.zip](https://github.com/Expugn/S-argo/files/1546865/Settings.zip)

**Comment by Expugn** [comment]
Thanks for the details!

I actually have never seen that error before, so I'm not entirely sure how to fix it but i'm sure we'll figure it out. Your settings file looks good too so there shouldn't be a problem there.

I was able to successfully create a new copy of the bot from scratch.  
Is your folder similar to this? https://i.imgur.com/JyCyXLD.png

**Comment by Expugn** [comment]
I tried to execute the .jar file by right clicking it -> open with -> Java(TM) Platform SE binary like you did, but it didn't work.

If the above comment isn't the solution then can you try double-clicking the .jar file instead?

**Comment by isaaclim98** [comment]
Perhaps the problem might be what I use to open the .jar file, since currently WinRAR is the default program for .jar files on my computer. My folder is the same as the one in your picture, except that double-clicking the .jar file would open its contents in WinRAR instead of Java. I'll go try a few different "Open With" programs of Java and get back to you soon! (Hopefully with it fixed haha) Thanks for the support and help! :)

**Comment by Expugn** [comment]
Alright, let me know if you get it sorted out!

**Comment by isaaclim98** [comment]
Heya, the .jar file finally works, what I did was as I said earlier, trying to open the file using all the different .exe files (with the word java in them) in the java's installation path folder. After waiting for quite a long while, it now works! Sorry I can't pinpoint exactly which .exe file it is, since I pretty much tried all of them, but thank you so much for the help!! :)

**Comment by Expugn** [comment]
Awesome! Glad it worked out in the end.

**Comment by isaaclim98** [comment]
Thank you! And have a great day! :)
