### ISSUE TITLE
Unable to update with command (part of starting Argo for the 2nd Time)

### ISSUE THREAD

**Issue by KyoRocks** [Expugn/S-argo#8]
Please review the info for Bug Reports in CONTRIBUTING.md before submitting
your issue. Thank you!

### Bot Version
S.argo.v2.11

### Type of Issue
Unable to update

### Bug Summary
Followed the guide and got up to "Starting Up S'argo For The Second Time".  After running the .jar file again.  The Bot indeed went online, and the two image folders appeared.  However we were unable to Run the command "update r" to grab the latest Banners.xml file and all the new images automatically.

This is where we got stuck.  Nothing happened.  It appears update r, @YourBotName update r OR $update r  also did not work.

### How to Reproduce the Issue
[INSTRUCTIONS ON HOW TO REPRODUCE THE ISSUE HERE]

Comments:  I apologize.  I just don't know what I did wrong.  I am reading that there is a settings.xml file and banner.xml file.  I don't see those as part of the files created.

**Comment by Expugn** [comment]
does the bot have permissions in the channel you're trying to run the command in?

make sure it has:
```
Send Messages
Manage Messages
Embed Links
Attach Files

and Read Messages/Read Message History in the channel you're sending the commands to

OR a role w/ Administrator
```

**Comment by KyoRocks** [comment]
Yeah that's the first thing I checked.  It has all the ones listed in the guide.

**Comment by KyoRocks** [comment]
Just so we are clear.  These were the ones listed in the guide:  
Send Messages
Manage Messages
Embed Links
Attach Files

**Comment by KyoRocks** [comment]
Ok so someone told me to try and go to the link in the login:  https://raw.githubusercontent.com/Expugn/S-argo_Data_v2/master/
 Is this link wrong.  I can't even open it in my browser.

**Comment by KyoRocks** [comment]
The issue was figured out.  I had the wrong ID.  The only thing we are having a problem now is that it is repeating the messages 4 times.  I'm going to delete and reinstall the bot to see if that resolves it.

**Comment by Expugn** [comment]
that link (https://raw.githubusercontent.com/Expugn/S-argo_Data_v2/master/) isnt meant to be visited by a browser. you're fine.

As for the bot repeating messages 4 times, you probably have 4 instances of the bot open. You'll need to kill the java processes in task manager (Ctrl + Shift + Esc) or just restart your computer if you don't want to mess something up.

**Comment by KyoRocks** [comment]
Reinstalling it got rid of the duplicate messages

**Comment by KyoRocks** [comment]
Ah didn't see your message.  So it can happen again.  Thanks
