### ISSUE TITLE
Update r doesnt work

### ISSUE THREAD

**Issue by UnstableWifi** [Expugn/S-argo#9]
update r doesnt do anything it doesnt seem to be doing anything either

**Comment by Expugn** [comment]
are you adding the command prefix before `update r`?

just typing `update r` won't work, you'll need to type (by default) `$update r`. replace `$` with whatever you have set as your `command prefix`.

if that's not the case, make sure your bot has permissions to:
```
Read Messages
Send Messages
Manage Messages
```
in the channel you're sending the command to.

**Comment by UnstableWifi** [comment]
yes i have been $update r and it doesnt work
just to make sure i can just download the 3.1v and go from there with the steps right

**Comment by Expugn** [comment]
yep, downloading v3.1 and following the startup guide should still work.

**Comment by UnstableWifi** [comment]
you might want to change up the guide a bit. the bot creation thing has changed.

**Comment by Expugn** [comment]
thanks for the heads up! I'll modify it later as soon as I can

**Comment by UnstableWifi** [comment]
for the bot owner its basically my discord name and the 4 numbers correct

**Comment by UnstableWifi** [comment]
how do i know if the update r command goes through

**Comment by Expugn** [comment]
incorrect, the bot owner ID is NOT your discord name and discriminator. If that's what you put for your bot owner ID, that's why it isnt working

from the startup guide:
```
Replace BOT_OWNER_DISCORD_ID_HERE with your Discord User ID.
If you don't know what your Discord ID is, go to User Settings -> Appearance in your Discord client and turn on Developer Mode which is located under the Advanced category.
Once Developer Mode is enabled, you can now right click your name/profile picture and click Copy ID.
```

you will know if the `update r` command goes through when the bot sends a message.

**Comment by UnstableWifi** [comment]
right click doesnt show anything unless im click the wrong place
its the same name/profile next to user settings right?

**Comment by UnstableWifi** [comment]
nvm i got it

**Comment by UnstableWifi** [comment]
i think i got it thx if i need help ill msg again thx!

**Comment by Expugn** [comment]
awesome, no problem!
